server:
  port: 1150

---
spring:
  profiles:
    active: local-dev
    
---
spring:
  profiles: dev
  datasource:
    url : jdbc:postgresql://john.db.elephantsql.com:5432/upnhxmem 
    username : upnhxmem
    password :  sXJdYo6R1Xg87fcJThvspMN0hlVRrMhs
  jpa:
    properties:
      hibernate:
       format_sql: true
    show-sql: true
    hibernate.ddl-auto : update
      
---
spring:
  profiles: local-dev
  datasource:
    url : jdbc:postgresql://localhost:5432/Blogs
    username : postgres
    password :  1234
  jpa:
    properties:
      hibernate:
       format_sql: true
    show-sql: true
    hibernate.ddl-auto : update
      
---

