server:
  port: 1150


app:
  upload:
    path: images

spring:
  servlet:
    multipart:
      max-file-size: 512KB
      max-request-size: 512KB
---
spring:
  profiles:
    active: local-dev
    
---
spring:
  profiles: dev
  datasource:
    url : jdbc:postgresql://john.db.elephantsql.com:5432/upnhxmem 
    username : upnhxmem
    password :  sXJdYo6R1Xg87fcJThvspMN0hlVRrMhs
  jpa:
    properties:
      hibernate:
       format_sql: true
    show-sql: true
    hibernate.ddl-auto : update
      
---
spring:
  profiles: local-dev
  datasource:
    url : jdbc:postgresql://localhost:5432/Demo
    username : postgres
    password :  1234
  jpa:
    properties:
      hibernate:
       format_sql: true
    show-sql: true
    hibernate.ddl-auto : update
      
---
spring:
  profiles: test
  datasource:
    url : jdbc:h2:mem:iblurblur 
    username : sa
    password : Tel1234!
  jpa:
    properties:
      hibernate:
       format_sql: true
    show-sql: true
    hibernate.ddl-auto : create-drop
  h2:
    console:
     enabled: true
---
spring:
  profiles: prod
  datasource:
    url : jdbc:postgresql://arjuna.db.elephantsql.com:5432/nppofghn 
    username : nppofghn
    password : Iq8zGrYqQStuRjJzYQN8vyhyL5-QiJA-
  jpa:
      hibernate.ddl-auto : update
      
server:
  port: 5000
---